# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:2BaDgEMGQj@tcp(127.0.0.1:3306)/test"
        #        注释掉tables，则生成所有表对应的数据
        #        tables: "user"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
