// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Goods is the golang structure for table goods.
type Goods struct {
	Id          int         `json:"id"          description:"商品表id"`
	Name        string      `json:"name"        description:"商品名称"`
	Description string      `json:"description" description:"商品描述"`
	CreateAt    *gtime.Time `json:"createAt"    description:""`
	UpdateAt    *gtime.Time `json:"updateAt"    description:""`
}
